name: search
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  search_choices: ^1.0.17
  http: ^0.12.2
  flappy_search_bar: 1.4.1
  material_floating_search_bar: ^0.2.3
  provider: ^4.3.2+2
  implicitly_animated_reorderable_list: ^0.2.5
  material_design_icons_flutter: ^4.0.5345
  flutter_widget_from_html: ^0.5.1+5
  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.0
  firebase_admob: ^0.10.2
  shared_preferences: ^0.5.12+4
  get_it: ^1.0.3
  flutter_colorpicker: ^0.3.4

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  # ios: true
  # android: true
  # image_path_ios: "assets/icon/icon.png"
  # image_path_android: "assets/icon/icon.png"
  # adaptive_icon_background: "assets/icon/icon_background.png"
  # adaptive_icon_foreground: "assets/icon/icon_foreground.png"

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
