name: hans_wehr_dictionary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.9.2+43

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  http: ^0.13.1
  material_floating_search_bar: ^0.3.3
  provider: ^5.0.0
  implicitly_animated_reorderable_list: ^0.4.0-dev+4
  flutter_widget_from_html: ^0.6.0-rc.2021031201
  url_launcher: ^6.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  get_it: ^6.0.0
  share: ^2.0.1
  in_app_review: ^2.0.1
  flutter_colorpicker: ^0.4.0
  badges: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  # ios: true
  # android: true
  # image_path_ios: "assets/icon/icon.png"
  # image_path_android: "assets/icon/icon.png"
  # adaptive_icon_background: "assets/icon/icon_background.png"
  # adaptive_icon_foreground: "assets/icon/icon_foreground.png"

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Amiri
    fonts:
      - asset: fonts/Amiri-Regular.ttf
