name: hans_wehr_dictionary
description: "Hans Wehr Arabic-English Dictionary"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  flutter_riverpod: ^3.3.1
  path: ^1.9.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hanswehr.sqlite
